apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: spa
  name: spa
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
      #nodePort: 30000
  #type: NodePort
  selector:
    io.kompose.service: spa
---
# XC needs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: spa-claim0
  name: spa-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: spa
  name: spa
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spa
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: spa
    spec:
      containers:
        - image: weiliang1216/spa:latest
          name: spa
          ports:
            - containerPort: 9000
          resources: {}
          volumeMounts:
            - mountPath: /var/cache/nginx/
              name: spa-claim0
            - mountPath: /var/run
              name: spa-claim0
      restartPolicy: Always
      volumes:
        - name: spa-claim0
          persistentVolumeClaim:
            claimName: spa-claim0
